<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';
</script>

<Post>
  <article slot="post_content">
    <p>
      要將你在 Visual Studio Code (VSCode) 已安裝的 extensions 輸出成 TXT
      檔案，並在另一台裝置上安裝，你可以按照以下步驟進行：
    </p>
    <h3 id="bu4-zhou4-1-jiang1-yi3-an1-zhuang1-de-extensions-shu1-chu1-cheng2-txt-dang4-an4">
      <a href="#bu4-zhou4-1-jiang1-yi3-an1-zhuang1-de-extensions-shu1-chu1-cheng2-txt-dang4-an4">
        步驟 1: 將已安裝的 extensions 輸出成 TXT 檔案
      </a>
    </h3>
    <ol>
      <li><p>打開 VSCode。</p></li>
      <li>
        <p>
          打開終端機（
          <strong>Terminal</strong>
          ），可以使用快捷鍵
          <code class="inline-code-block">Ctrl +</code>
          （反引號）。
        </p>
      </li>
      <li>
        <p>
          輸入以下指令，將已安裝的 extensions 列表輸出到一個 <code class="inline-code-block">extensions-list.txt</code>
           檔案中：
        </p>
        <div class="code-block">
          <CodeCopy>
            <pre><code
                class="language-bash">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content">code --list-extensions <span class="token operator">></span> extensions-list.txt</div></div>`}</code></pre>
          </CodeCopy>
        </div>
      </li>
      <li>
        <p>
          在你的工作目錄下，會生成一個 <code class="inline-code-block">extensions-list.txt</code>
           檔案，裡面列出所有已安裝的 extensions。
        </p>
      </li>
    </ol>
    <h3 id="bu4-zhou4-2-zai4-ling4-yi1-tai2-zhuang1-zhi4-shang4-an1-zhuang1-extensions">
      <a href="#bu4-zhou4-2-zai4-ling4-yi1-tai2-zhuang1-zhi4-shang4-an1-zhuang1-extensions">
        步驟 2: 在另一台裝置上安裝 extensions
      </a>
    </h3>
    <ol>
      <li>
        <p>
          把 <code class="inline-code-block">extensions-list.txt</code>
           檔案複製到另一台裝置。
        </p>
      </li>
      <li>
        <p>
          打開另一台裝置的 VSCode 終端機，並執行以下指令，根據 <code class="inline-code-block">
            extensions-list.txt
          </code>
           中的列表安裝所有 extensions：
        </p>
        <div class="code-block">
          <CodeCopy>
            <pre><code
                class="language-bash">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content"><span class="token function">cat</span> extensions-list.txt <span class="token operator">|</span> <span class="token function">xargs</span> <span class="token parameter variable">-n</span> <span class="token number">1</span> code --install-extension</div></div>`}</code></pre>
          </CodeCopy>
        </div>
      </li>
    </ol>
    <p>這樣就可以批量安裝所有的 extensions 了！</p>
  </article>
</Post>
