<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';
</script>

<Post>
  <article slot="post_content">
    <h3 id="shang4-ke4-bi3-ji4"><a href="#shang4-ke4-bi3-ji4">上課筆記</a></h3>
    <p><ImgZoom src="\about\image.png" alt="alt text"></ImgZoom></p>
  </article>
</Post>
