<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';
</script>

<Post>
  <article slot="post_content">
    <h2 id="intro"><a href="#intro">✨ Intro</a></h2>
    <p>
      <a href="https://www.github.com/kwchang0831/svelte-QWER" rel="external">QWER</a>
      is simply an Awesome blog starter and static site generator. Built using
      <a href="https://kit.svelte.dev/" rel="external">SvelteKit</a>
       and Love ❤.
    </p>
    <h2 id="try-out-qwer"><a href="#try-out-qwer">🎉 Try out QWER</a></h2>
    <p>
      Create a QWER blog named <code class="inline-code-block">my-blog</code>
      .
    </p>
    <div class="code-block">
      <CodeCopy>
        <pre><code
            class="language-ts">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content"><span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token keyword">let</span> x <span class="token keyword">in</span> <span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">)</span> <span class="token builtin">console</span><span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>x<span class="token punctuation">)</span><span class="token punctuation">;</span></div></div>`}</code></pre>
      </CodeCopy>
    </div>
    <h2 id="to-dev"><a href="#to-dev">⚡️ To Dev</a></h2>
    <p><ImgZoom src="\note_react\image.png" alt="alt text"></ImgZoom></p>
  </article>
</Post>
